"""Payload-free Connected Change contracts, descriptors, and matching."""

from .accepted_plan import (
    ConnectedAcceptedFileMapping,
    FolderAcceptedPlanV2,
    build_connected_accepted_plan,
    validate_connected_accepted_plan,
)
from .contracts import (
    CapsuleAppliedExecutionOrigin,
    ConnectedChangeCore,
    ConnectedChangeCoreV2,
    ConnectedChangeError,
    ConnectedChangeFile,
    ConnectedChangeFileV2,
    ConnectedChangeLineageV1,
    ConnectedChangeLinkSlot,
    ConnectedChangeMatchMapping,
    ConnectedChangeMatchReport,
    ConnectedChangeMember,
    ConnectedChangeMemberBindingV1,
    FolderExecutionOrigin,
    GptPlannedExecutionOrigin,
)
from .descriptors import (
    ReceiverDescriptor,
    ReceiverLinkSlot,
    build_connected_change_core,
    build_connected_change_core_v2,
    build_connected_change_lineage,
    build_receiver_descriptors,
    create_connected_change_file,
    create_connected_change_file_v2,
    parse_connected_change_file,
    parse_connected_change_file_any,
    parse_connected_change_file_v2,
)
from .matcher import match_connected_change

__all__ = [
    "CapsuleAppliedExecutionOrigin",
    "ConnectedAcceptedFileMapping",
    "ConnectedChangeCore",
    "ConnectedChangeCoreV2",
    "ConnectedChangeError",
    "ConnectedChangeFile",
    "ConnectedChangeFileV2",
    "ConnectedChangeLineageV1",
    "ConnectedChangeLinkSlot",
    "ConnectedChangeMatchMapping",
    "ConnectedChangeMatchReport",
    "ConnectedChangeMember",
    "ConnectedChangeMemberBindingV1",
    "FolderExecutionOrigin",
    "FolderAcceptedPlanV2",
    "GptPlannedExecutionOrigin",
    "ReceiverDescriptor",
    "ReceiverLinkSlot",
    "build_connected_accepted_plan",
    "build_connected_change_core",
    "build_connected_change_core_v2",
    "build_connected_change_lineage",
    "build_receiver_descriptors",
    "create_connected_change_file",
    "create_connected_change_file_v2",
    "match_connected_change",
    "parse_connected_change_file",
    "parse_connected_change_file_any",
    "parse_connected_change_file_v2",
    "validate_connected_accepted_plan",
]
